name: Test
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
permissions:
  contents: read
jobs:
  test:
    name: test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: actions/checkout@v3
      - name: Install libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y opencl-headers ocl-icd-opencl-dev
      - name: Run tests
        run: go test -race ./...
